
books = {
    '1mose' : 'Genesis',
    '2mose' : 'Exodus',
    '3mose' : 'Leviticus',
    '4mose' : 'Numbers',
    '5mose' : 'Deuteronomy',
    'josua' : 'Joshua',
    'richter' : 'Judges',
    'rut' : 'Ruth',
    '1samuel' : 'I Samuel',
    '2samuel' : 'II Samuel',
    '1könige' : 'I Kings',
    '2könige' : 'II Kings',
    '1chronik' : 'I Chronicles',
    '2chronik' : 'II Chronicles',
    'esra' : 'Ezra',
    'nehemia' : 'Nehemiah',
    'esther' : 'Esther',
    'hiob' : 'Job',
    'psalm' : 'Psalms',
    'sprüche' : 'Proverbs',
    'prediger' : 'Ecclesiastes',
    'hohelied' : 'Song of Solomon',
    'jesaja' : 'Isaiah',
    'jeremia' : 'Jeremiah',
    'klagelieder' : 'Lamentations',
    'hesekiel' : 'Ezekiel',
    'daniel' : 'Daniel',
    'hosea' : 'Hosea',
    'joel' : 'Joel',
    'amos' : 'Amos',
    'obadja' : 'Obadiah',
    'jona' : 'Jonah',
    'micha' : 'Micah',
    'nahum' : 'Nahum',
    'habakuk' : 'Habakkuk',
    'zefanja' : 'Zephaniah',
    'haggai' : 'Haggai',
    'sacharja' : 'Zechariah',
    'maleachi' : 'Malachi',
    'matthäus' : 'Matthew',
    'markus' : 'Mark',
    'lukas' : 'Luke',
    'johannes' : 'John',
    'apostelgeschichte' : 'Acts',
    'römer' : 'Romans',
    '1korinther' : 'I Corinthians',
    '2korinther' : 'II Corinthians',
    'galater' : 'Galatians',
    'epheser' : 'Ephesians',
    'philipper' : 'Philippians',
    'kolosser' : 'Colossians',
    '1thessalonicher' : 'I Thessalonians',
    '2thessalonicher' : 'II Thessalonians',
    '1timotheus' : 'I Timothy',
    '2timotheus' : 'II Timothy',
    'titus' : 'Titus',
    'philemon' : 'Philemon',
    'hebräer' : 'Hebrews',
    'jakubusbrief' : 'James',
    '1petrus' : 'I Peter',
    '2petrus' : 'II Peter',
    '1johannes' : 'I John',
    '2johannes' : 'II John',
    '3johannes' : 'III John',
    'judas' : 'Jude',
    'offenbarung' : 'Revelation of John',
}
